version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn clean
      - mvn compile
  post_build:
    commands:
      - echo Build completed
      - mvn package
artifacts:
  files:
    - 'target/Practice-0.0.1-SNAPSHOT.jar'
  
